# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [26]:
# Import torch
import torch

# Create random tensor
torch.manual_seed(23)
rand_tensor_1 = torch.rand(7,7)
print(rand_tensor_1)
print(torch.rand(1))



tensor([[0.4283, 0.2889, 0.4224, 0.3571, 0.9577, 0.1100, 0.2933],
        [0.9205, 0.5876, 0.1299, 0.6729, 0.1028, 0.7876, 0.5540],
        [0.4653, 0.2311, 0.2214, 0.3348, 0.4541, 0.2519, 0.6310],
        [0.1707, 0.3122, 0.1976, 0.5466, 0.0213, 0.9049, 0.8444],
        [0.9330, 0.2950, 0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
        [0.1879, 0.4546, 0.1049, 0.7112, 0.7709, 0.5514, 0.0807],
        [0.3029, 0.7935, 0.2823, 0.5686, 0.1354, 0.4224, 0.1946]])
tensor([0.0791])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [32]:
# Create another random tensor
torch.manual_seed(23)
print(torch.rand(1))

rand_tensor_2 = torch.rand(1,7)

# Perform matrix multiplication 
torch.matmul(rand_tensor_1, torch.t(rand_tensor_2))


tensor([0.4283])


tensor([[1.1461],
        [1.9572],
        [1.3364],
        [1.8203],
        [1.8652],
        [1.2857],
        [1.3859]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [34]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_1 = torch.rand(7,7)
rand_2 = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(rand_1, torch.t(rand_2))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [36]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [38]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()


# Create two random tensors on GPU
rand_3 = torch.rand(2,3)
rand_4 = torch.rand(2,3)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [42]:
# Perform matmul on tensor_A and tensor_B
rand_5 = torch.matmul(rand_3, torch.t(rand_4))
rand_5

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [44]:
# Find max
torch.max(rand_5)
# Find min
torch.min(rand_5)

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [46]:
# Find arg max
torch.argmax(rand_5)

# Find arg min
torch.argmin(rand_5)

tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [47]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_6 = torch.rand(1,1,1,10)

# Remove single dimensions
torch.squeeze(rand_6)

# Print out tensors and their shapes


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])